### ISSUE TITLE
Build font without JP characters

### ISSUE THREAD

**Issue by hpdipto** [yuru7/PlemolJP#25]
Hi, how can I build the font without JP characters?
Thanks in advance!

**Comment by hpdipto** [comment]
Sorry my bad. I didn't understand the build process properly. When building the font with `fontforge_script.py` script, eng font are already separated.

**Comment by yuru7** [comment]
When I run fontforge_script.py, the eng font is separated, but some glyphs are missing due to compositing.

![image](https://github.com/user-attachments/assets/097c6d29-47e0-4d3c-9dcf-1082b1d03a97)

So I think it would be better to modify fontforge_script.py a little and run it.

1. comment out the delete_duplicate_glyphs() part
   https://github.com/yuru7/PlemolJP/blob/main/fontforge_script.py#L219-L220
2. run with `--console` build option
   Example: `fontforge fontforge_script.py --console`

Check the generated `fontforge_PlemolJPConsole-Regular-eng.ttf`.
